from . import discuss_channel
from . import res_users
from . import res_partner
from . import mail_message
from . import tools
from . import completions
from . import utils
from . import ir_ui_view
from . import calendar_event
